### ISSUE TITLE
zsh_autosuggest_invoke_original_widget:9: history-search-multi-word: function definition file not found

### ISSUE THREAD

**Issue by kakulukia** [zdharma/history-search-multi-word#17]
I just freshly cloned this repo and tried to activate this plugin in my oh-my-zsh shell, but i get this instead .. how can this be fixed?

All should be where its supposed to:
![Bildschirmfoto 2019-10-16 um 11 56 39](https://user-images.githubusercontent.com/96352/66908836-0f640e00-f00c-11e9-8742-36203672464b.png)

**Comment by Rayqan** [comment]
It appears to be an issue with the id-as ice, I had the same issue.

**Comment by kakulukia** [comment]
I also managed to fix it somehow .. dont remember what i did tho and forgot to update the ticket ..
