### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by lovesegfault** [zdharma/history-search-multi-word#18]
The latest tag is ancient, which makes packaging rely either on an old version, or have to tag the latest commit.

**Comment by psprint** [comment]
Done. Thanks for reminding me. Can I ask for which packages is the request?

**Comment by lovesegfault** [comment]
I'm packaging all the zsh plugins I use, which includes this one, for [NixOS](https://nixos.org/)

**Comment by lovesegfault** [comment]
Thank you!!
