### ISSUE TITLE
Ctrl-C while searching crashes ZSH

### ISSUE THREAD

**Issue by rnc** [zdharma/history-search-multi-word#2]
Using zsh 5.1.1 (from Fedora 23).

**Comment by psprint** [comment]
A coincidence, today I've installed Fedora 23 on Virtual Box. Have zsh-5.1.1 and Ctrl-C doesn't cause crash. Any more data is welcomed. Sorry for the problem, you might use full fledged multi-word searcher from zsh-navigation-tools, it's based on curses library and free from any Zle  issues.

**Comment by psprint** [comment]
That said I've just spotted a suspicious code, could you try current version (also made a new release v0.81)

**Comment by mjklemm** [comment]
Hi, 
I have a similar problem with zsh 5.0.2.  On my CentOS machines, Ctrl-C does not abort search. On some machines it simply goes to the next entry in the search list. On other machines it does nothing (aparently). Any hints where this might be coming from are highly appreciated! 
Cheers,
-michael

**Comment by psprint** [comment]
@mjklemm: I recently worked with Zsh Hackers to resolve this and future release 5.3 will have Ctrl-C flawlessly working. I also applied a workaround patch to HSMW, not sure if it helps, could you update and try?

**Comment by mjklemm** [comment]
I have installed zsh 5.2 and on one machine it know seems to work much better.  I will try the other machines next. Thanks for your quick help on this.

**Comment by psprint** [comment]
@mjklemm: With the update I was referring to HSMW itself – i.e. git pull

**Comment by tywtyw2002** [comment]
Q: How to cancel(close) the history search?

By the normal history search in zsh, I can use Ctrl+C to cancel the current history search, but in history-search-multi-word, who to cancel the search?

**Comment by psprint** [comment]
@tywtyw2002: Ctrl-C should work. There's bug in Zsh that can cause problems (fixed in upcoming version of Zsh, 5.3). However current HSMW has workaround for Zsh <= 5.2 and Ctrl-C should work with only small problems.
