### ISSUE TITLE
no such widget: hsmw-saved-zle-line-pre-redraw 

### ISSUE THREAD

**Issue by hdkiller** [zdharma/history-search-multi-word#21]
Hello!

After CTRL+R search I select the result press enter, and above the prompt the following error message appears:

history-search-multi-word:zle:439: no such widget `hsmw-saved-zle-line-pre-redraw'

**Comment by psprint** [comment]
The issue has been already fixed, try updating the plugin.

**Comment by hdkiller** [comment]
I must be doing something wrong. I have updated the plugin, I using antigen, so i just did a 

antigen update

I see the latest commit in ~/.antigen/bundles/zdharma/history-search-multi-word/. so the update successed. I restarted zsh and the issue persist.

**Comment by psprint** [comment]
The line number in the error suggests that the plugin isn't updated. The
commit should be:

2020-01-15 ee864ea hsmw: Test for line-pre-redraw first

is it like this?

**Comment by hdkiller** [comment]
Yes, thats the latest commit I have. On other boxes its working fine after the update, so something wrong at my side. Thanks a lot, please close this issue. BTW your plugin is awesome!
