### ISSUE TITLE
don't erase search query when exiting HSMW

### ISSUE THREAD

**Issue by sunaku** [zdharma/history-search-multi-word#7]
Hello,

I like to type my search query on the command line _**before**_ pressing Ctrl+R to activate HSMW.  However, when I exit HSMW without choosing a history item to run (by pressing Ctrl+C), the entire command line is automatically cleared and my query is lost. :scream:  Please provide a way to disable such automatic clearing. :sweat_smile:

Thanks for your consideration.

**Comment by psprint** [comment]
Implemented. Default behavior is like you described, no clearing of command line. To change to previous behavior:

```zsh
zstyle ":plugin:history-search-multi-word" clear-on-cancel "yes"
```

**Comment by sunaku** [comment]
:+1: It's perfect! :100: Thank you! :bowing_man:
